/* Migration: service bookings full schema and upgrades */
CREATE TABLE IF NOT EXISTS service_bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  booking_reference VARCHAR(150) UNIQUE,
  provider_id INT NOT NULL,
  service_id INT NOT NULL,
  user_id INT NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(100) NOT NULL,
  alternate_phone VARCHAR(100) DEFAULT NULL,
  service_date DATE NOT NULL,
  service_time VARCHAR(50) NOT NULL,
  address TEXT NOT NULL,
  notes TEXT DEFAULT NULL,
  property_type VARCHAR(100) DEFAULT NULL,
  room_count INT DEFAULT NULL,
  urgency_level VARCHAR(100) DEFAULT NULL,
  amount DECIMAL(12,2) DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'NGN',
  payment_status ENUM('unpaid','awaiting_payment','paid','failed','refunded') NOT NULL DEFAULT 'unpaid',
  booking_status ENUM('pending','accepted','awaiting_payment','rejected','cancelled','in_progress','completed','confirmed') NOT NULL DEFAULT 'pending',
  provider_response_note TEXT DEFAULT NULL,
  paystack_reference VARCHAR(150) DEFAULT NULL,
  paid_at DATETIME DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_provider_id (provider_id),
  INDEX idx_user_id (user_id),
  INDEX idx_service_id (service_id),
  INDEX idx_booking_reference (booking_reference)
);
